const allDepartments = [{ enabled : false, department: "Administration Office, Executive Office of the President"},
{ enabled : false, department: "Administrative Conference of the United States"},
{ enabled : false, department: "Administrative Office of United States Courts"},
{ enabled : false, department: "Advisory Council on Historic Preservation"},
{ enabled : false, department: "Advocacy and Outreach Office"},
{ enabled : false, department: "African Development Foundation"},
{ enabled : false, department: "Agency for Healthcare Research and Quality"},
{ enabled : false, department: "Agency for International Development"},
{ enabled : false, department: "Agency for Toxic Substances and Disease Registry"},
{ enabled : false, department: "Aging Administration"},
{ enabled : false, department: "Agricultural Marketing Service"},
{ enabled : false, department: "Agricultural Research Service"},
{ enabled : false, department: "Agriculture Department"},
{ enabled : false, department: "Air Force Department"},
{ enabled : false, department: "Air Quality National Commission"},
{ enabled : false, department: "Air Transportation Stabilization Board"},
{ enabled : false, department: "Alaska Power Administration"},
{ enabled : false, department: "Alcohol and Tobacco Tax and Trade Bureau"},
{ enabled : false, department: "Alcohol, Tobacco, Firearms, and Explosives Bureau"},
{ enabled : false, department: "American Battle Monuments Commission"},
{ enabled : false, department: "Amtrak Reform Council"},
{ enabled : false, department: "Animal and Plant Health Inspection Service"},
{ enabled : false, department: "Antitrust Division"},
{ enabled : false, department: "Antitrust Modernization Commission"},
{ enabled : false, department: "Appalachian Regional Commission"},
{ enabled : false, department: "Appalachian States Low-Level Radioactive Waste Commission"},
{ enabled : false, department: "Architect of the Capitol"},
{ enabled : false, department: "Architectural and Transportation Barriers Compliance Board"},
{ enabled : false, department: "Arctic Research Commission"},
{ enabled : false, department: "Armed Forces Retirement Home"},
{ enabled : false, department: "Arms Control and Disarmament Agency"},
{ enabled : false, department: "Army Department"},
{ enabled : false, department: "Assassination Records Review Board"},
{ enabled : false, department: "Barry M. Goldwater Scholarship and Excellence in Education Foundation"},
{ enabled : false, department: "Benefits Review Board"},
{ enabled : false, department: "Bipartisan Commission on Entitlement and Tax Reform"},
{ enabled : false, department: "Board of Directors of the Hope for Homeowners Program"},
{ enabled : false, department: "Bonneville Power Administration"},
{ enabled : false, department: "Broadcasting Board of Governors"},
{ enabled : false, department: "Bureau of the Fiscal Service"},
{ enabled : false, department: "Census Bureau"},
{ enabled : false, department: "Census Monitoring Board"},
{ enabled : false, department: "Centers for Disease Control and Prevention"},
{ enabled : false, department: "Centers for Medicare & Medicaid Services"},
{ enabled : false, department: "Central Intelligence Agency"},
{ enabled : false, department: "Chemical Safety and Hazard Investigation Board"},
{ enabled : false, department: "Child Support Enforcement Office"},
{ enabled : false, department: "Children and Families Administration"},
{ enabled : false, department: "Christopher Columbus Quincentenary Jubilee Commission"},
{ enabled : false, department: "Civil Rights Commission"},
{ enabled : false, department: "Coast Guard"},
{ enabled : false, department: "Commerce Department"},
{ enabled : false, department: "Commercial Space Transportation Office"},
{ enabled : false, department: "Commission of Fine Arts"},
{ enabled : false, department: "Commission on Immigration Reform"},
{ enabled : false, department: "Commission on Protecting and Reducing Government Secrecy"},
{ enabled : false, department: "Commission on Review of Overseas Military Facility Structure of the United States"},
{ enabled : false, department: "Commission on Structural Alternatives for the Federal Courts of Appeals"},
{ enabled : false, department: "Commission on the Advancement of Federal Law Enforcement"},
{ enabled : false, department: "Commission on the Bicentennial of the United States Constitution"},
{ enabled : false, department: "Commission on the Future of the United States Aerospace Industry"},
{ enabled : false, department: "Commission on the Social Security Notch Issue"},
{ enabled : false, department: "Committee for Purchase From People Who Are Blind or Severely Disabled"},
{ enabled : false, department: "Committee for the Implementation of Textile Agreements"},
{ enabled : false, department: "Commodity Credit Corporation"},
{ enabled : false, department: "Commodity Futures Trading Commission"},
{ enabled : false, department: "Community Development Financial Institutions Fund"},
{ enabled : false, department: "Community Living Administration"},
{ enabled : false, department: "Competitiveness Policy Council"},
{ enabled : false, department: "Comptroller of the Currency"},
{ enabled : false, department: "Congressional Budget Office"},
{ enabled : false, department: "Consumer Financial Protection Bureau"},
{ enabled : false, department: "Consumer Product Safety Commission"},
{ enabled : false, department: "Cooperative State Research, Education, and Extension Service"},
{ enabled : false, department: "Coordinating Council on Juvenile Justice and Delinquency Prevention"},
{ enabled : false, department: "Copyright Office, Library of Congress"},
{ enabled : false, department: "Copyright Royalty Board"},
{ enabled : false, department: "Copyright Royalty Judges"},
{ enabled : false, department: "Corporation for National and Community Service"},
{ enabled : false, department: "Council of the Inspectors General on Integrity and Efficiency"},
{ enabled : false, department: "Council on Environmental Quality"},
{ enabled : false, department: "Counsel to the President"},
{ enabled : false, department: "Court Services and Offender Supervision Agency for the District of Columbia"},
{ enabled : false, department: "Crime and Security in U.S. Seaports, Interagency Commission"},
{ enabled : false, department: "Customs Service"},
{ enabled : false, department: "Defense Acquisition Regulations System"},
{ enabled : false, department: "Defense Base Closure and Realignment Commission"},
{ enabled : false, department: "Defense Contract Audit Agency"},
{ enabled : false, department: "Defense Criminal Investigative Service"},
{ enabled : false, department: "Defense Department"},
{ enabled : false, department: "Defense Information Systems Agency"},
{ enabled : false, department: "Defense Intelligence Agency"},
{ enabled : false, department: "Defense Investigative Service"},
{ enabled : false, department: "Defense Logistics Agency"},
{ enabled : false, department: "Defense Mapping Agency"},
{ enabled : false, department: "Defense Nuclear Facilities Safety Board"},
{ enabled : false, department: "Defense Special Weapons Agency"},
{ enabled : false, department: "Delaware River Basin Commission"},
{ enabled : false, department: "Denali Commission"},
{ enabled : false, department: "Disability Employment Policy Office"},
{ enabled : false, department: "Drug Enforcement Administration"},
{ enabled : false, department: "Economic Analysis Bureau"},
{ enabled : false, department: "Economic Analysis Staff"},
{ enabled : false, department: "Economic Development Administration"},
{ enabled : false, department: "Economic Research Service"},
{ enabled : false, department: "Economics and Statistics Administration"},
{ enabled : false, department: "Education Department"},
{ enabled : false, department: "Election Assistance Commission"},
{ enabled : false, department: "Electronic Commerce Advisory Commission"},
{ enabled : false, department: "Emergency Oil and Gas Guaranteed Loan Board"},
{ enabled : false, department: "Emergency Steel Guarantee Loan Board"},
{ enabled : false, department: "Employee Benefits Security Administration"},
{ enabled : false, department: "Employees Compensation Appeals Board"},
{ enabled : false, department: "Employment and Training Administration"},
{ enabled : false, department: "Employment Standards Administration"},
{ enabled : false, department: "Energy Department"},
{ enabled : false, department: "Energy Efficiency and Renewable Energy Office"},
{ enabled : false, department: "Energy Information Administration"},
{ enabled : false, department: "Energy Policy and New Uses Office"},
{ enabled : false, department: "Energy Research Office"},
{ enabled : false, department: "Engineers Corps"},
{ enabled : false, department: "Engraving and Printing Bureau"},
{ enabled : false, department: "Environment Office, Energy Department"},
{ enabled : false, department: "Environmental Protection Agency"},
{ enabled : false, department: "Equal Employment Opportunity Commission"},
{ enabled : false, department: "Executive Council on Integrity and Efficiency"},
{ enabled : false, department: "Executive Office for Immigration Review"},
{ enabled : false, department: "Executive Office of the President"},
{ enabled : false, department: "Export Administration Bureau"},
{ enabled : false, department: "Export-Import Bank"},
{ enabled : false, department: "Family Assistance Office"},
{ enabled : false, department: "Farm Credit Administration"},
{ enabled : false, department: "Farm Credit System Insurance Corporation"},
{ enabled : false, department: "Farm Service Agency"},
{ enabled : false, department: "Federal Accounting Standards Advisory Board"},
{ enabled : false, department: "Federal Acquisition Regulation System"},
{ enabled : false, department: "Federal Aviation Administration"},
{ enabled : false, department: "Federal Bureau of Investigation"},
{ enabled : false, department: "Federal Communications Commission"},
{ enabled : false, department: "Federal Contract Compliance Programs Office"},
{ enabled : false, department: "Federal Council on the Arts and the Humanities"},
{ enabled : false, department: "Federal Crop Insurance Corporation"},
{ enabled : false, department: "Federal Deposit Insurance Corporation"},
{ enabled : false, department: "Federal Election Commission"},
{ enabled : false, department: "Federal Emergency Management Agency"},
{ enabled : false, department: "Federal Energy Regulatory Commission"},
{ enabled : false, department: "Federal Financial Institutions Examination Council"},
{ enabled : false, department: "Federal Highway Administration"},
{ enabled : false, department: "Federal Housing Enterprise Oversight Office"},
{ enabled : false, department: "Federal Housing Finance Agency"},
{ enabled : false, department: "Federal Housing Finance Board"},
{ enabled : false, department: "Federal Labor Relations Authority"},
{ enabled : false, department: "Federal Law Enforcement Training Center"},
{ enabled : false, department: "Federal Maritime Commission"},
{ enabled : false, department: "Federal Mediation and Conciliation Service"},
{ enabled : false, department: "Federal Mine Safety and Health Review Commission"},
{ enabled : false, department: "Federal Motor Carrier Safety Administration"},
{ enabled : false, department: "Federal Pay, Advisory Committee"},
{ enabled : false, department: "Federal Permitting Improvement Steering Council"},
{ enabled : false, department: "Federal Prison Industries"},
{ enabled : false, department: "Federal Procurement Policy Office"},
{ enabled : false, department: "Federal Railroad Administration"},
{ enabled : false, department: "Federal Register Office"},
{ enabled : false, department: "Federal Register, Administrative Committee"},
{ enabled : false, department: "Federal Reserve System"},
{ enabled : false, department: "Federal Retirement Thrift Investment Board"},
{ enabled : false, department: "Federal Service Impasses Panel"},
{ enabled : false, department: "Federal Trade Commission"},
{ enabled : false, department: "Federal Transit Administration"},
{ enabled : false, department: "Financial Crimes Enforcement Network"},
{ enabled : false, department: "Financial Crisis Inquiry Commission"},
{ enabled : false, department: "Financial Research Office"},
{ enabled : false, department: "Financial Stability Oversight Council"},
{ enabled : false, department: "First Responder Network Authority"},
{ enabled : false, department: "Fiscal Service"},
{ enabled : false, department: "Fish and Wildlife Service"},
{ enabled : false, department: "Food and Consumer Service"},
{ enabled : false, department: "Food and Drug Administration"},
{ enabled : false, department: "Food and Nutrition Service"},
{ enabled : false, department: "Food Safety and Inspection Service"},
{ enabled : false, department: "Foreign Agricultural Service"},
{ enabled : false, department: "Foreign Assets Control Office"},
{ enabled : false, department: "Foreign Claims Settlement Commission"},
{ enabled : false, department: "Foreign Service Grievance Board"},
{ enabled : false, department: "Foreign Service Impasse Disputes Panel"},
{ enabled : false, department: "Foreign Service Labor Relations Board"},
{ enabled : false, department: "Foreign-Trade Zones Board"},
{ enabled : false, department: "Forest Service"},
{ enabled : false, department: "General Services Administration"},
{ enabled : false, department: "Geographic Names Board"},
{ enabled : false, department: "Geological Survey"},
{ enabled : false, department: "Government Accountability Office"},
{ enabled : false, department: "Government Ethics Office"},
{ enabled : false, department: "Government National Mortgage Association"},
{ enabled : false, department: "Government Publishing Office"},
{ enabled : false, department: "Grain Inspection, Packers and Stockyards Administration"},
{ enabled : false, department: "Gulf Coast Ecosystem Restoration Council"},
{ enabled : false, department: "Harry S. Truman Scholarship Foundation"},
{ enabled : false, department: "Health and Human Services Department"},
{ enabled : false, department: "Health Care Finance Administration"},
{ enabled : false, department: "Health Resources and Services Administration"},
{ enabled : false, department: "Hearings and Appeals Office, Energy Department"},
{ enabled : false, department: "Hearings and Appeals Office, Interior Department"},
{ enabled : false, department: "Homeland Security Department"},
{ enabled : false, department: "Housing and Urban Development Department"},
{ enabled : false, department: "Immigration and Naturalization Service"},
{ enabled : false, department: "Indian Affairs Bureau"},
{ enabled : false, department: "Indian Arts and Crafts Board"},
{ enabled : false, department: "Indian Health Service"},
{ enabled : false, department: "Indian Trust Transition Office"},
{ enabled : false, department: "Industry and Security Bureau"},
{ enabled : false, department: "Information Security Oversight Office"},
{ enabled : false, department: "Inspector General Office, Agriculture Department"},
{ enabled : false, department: "Inspector General Office, Health and Human Services Department"},
{ enabled : false, department: "Institute of American Indian and Alaska Native Culture and Arts Development"},
{ enabled : false, department: "Institute of Museum and Library Services"},
{ enabled : false, department: "Inter-American Foundation"},
{ enabled : false, department: "Interagency Floodplain Management Review Committee"},
{ enabled : false, department: "Intergovernmental Relations Advisory Commission"},
{ enabled : false, department: "Interior Department"},
{ enabled : false, department: "Internal Revenue Service"},
{ enabled : false, department: "International Boundary and Water Commission, United States and Mexico"},
{ enabled : false, department: "International Broadcasting Board"},
{ enabled : false, department: "International Development Cooperation Agency"},
{ enabled : false, department: "International Investment Office"},
{ enabled : false, department: "International Joint Commission-United States and Canada"},
{ enabled : false, department: "International Organizations Employees Loyalty Board"},
{ enabled : false, department: "International Trade Administration"},
{ enabled : false, department: "International Trade Commission"},
{ enabled : false, department: "Interstate Commerce Commission"},
{ enabled : false, department: "James Madison Memorial Fellowship Foundation"},
{ enabled : false, department: "Japan-United States Friendship Commission"},
{ enabled : false, department: "Joint Board for Enrollment of Actuaries"},
{ enabled : false, department: "Judicial Conference of the United States"},
{ enabled : false, department: "Judicial Review Commission on Foreign Asset Control"},
{ enabled : false, department: "Justice Department"},
{ enabled : false, department: "Justice Programs Office"},
{ enabled : false, department: "Juvenile Justice and Delinquency Prevention Office"},
{ enabled : false, department: "Labor Department"},
{ enabled : false, department: "Labor Statistics Bureau"},
{ enabled : false, department: "Labor-Management Standards Office"},
{ enabled : false, department: "Land Management Bureau"},
{ enabled : false, department: "Legal Services Corporation"},
{ enabled : false, department: "Library of Congress"},
{ enabled : false, department: "Local Television Loan Guarantee Board"},
{ enabled : false, department: "Management and Budget Office"},
{ enabled : false, department: "Marine Mammal Commission"},
{ enabled : false, department: "Maritime Administration"},
{ enabled : false, department: "Medicare Payment Advisory Commission"},
{ enabled : false, department: "Merit Systems Protection Board"},
{ enabled : false, department: "Military Compensation and Retirement Modernization Commission"},
{ enabled : false, department: "Millennium Challenge Corporation"},
{ enabled : false, department: "Mine Safety and Health Administration"},
{ enabled : false, department: "Minerals Management Service"},
{ enabled : false, department: "Mines Bureau"},
{ enabled : false, department: "Minority Business Development Agency"},
{ enabled : false, department: "Minority Economic Impact Office"},
{ enabled : false, department: "Mississippi River Commission"},
{ enabled : false, department: "Monetary Offices"},
{ enabled : false, department: "Morris K. Udall and Stewart L. Udall Foundation"},
{ enabled : false, department: "National Aeronautics and Space Administration"},
{ enabled : false, department: "National Agricultural Library"},
{ enabled : false, department: "National Agricultural Statistics Service"},
{ enabled : false, department: "National Archives and Records Administration"},
{ enabled : false, department: "National Bankruptcy Review Commission"},
{ enabled : false, department: "National Biological Service"},
{ enabled : false, department: "National Bipartisan Commission on Future of Medicare"},
{ enabled : false, department: "National Capital Planning Commission"},
{ enabled : false, department: "National Civilian Community Corps"},
{ enabled : false, department: "National Commission on Fiscal Responsibility and Reform"},
{ enabled : false, department: "National Commission on Intermodal Transportation"},
{ enabled : false, department: "National Commission on Libraries and Information Science"},
{ enabled : false, department: "National Commission on Manufactured Housing"},
{ enabled : false, department: "National Commission on Military, National, and Public Service"},
{ enabled : false, department: "National Commission on Terrorist Attacks Upon the United States"},
{ enabled : false, department: "National Commission on the Cost of Higher Education"},
{ enabled : false, department: "National Communications System"},
{ enabled : false, department: "National Consumer Cooperative Bank"},
{ enabled : false, department: "National Council on Disability"},
{ enabled : false, department: "National Counterintelligence Center"},
{ enabled : false, department: "National Credit Union Administration"},
{ enabled : false, department: "National Crime Prevention and Privacy Compact Council"},
{ enabled : false, department: "National Economic Council"},
{ enabled : false, department: "National Education Goals Panel"},
{ enabled : false, department: "National Endowment for the Arts"},
{ enabled : false, department: "National Endowment for the Humanities"},
{ enabled : false, department: "National Foundation on the Arts and the Humanities"},
{ enabled : false, department: "National Gambling Impact Study Commission"},
{ enabled : false, department: "National Geospatial-Intelligence Agency"},
{ enabled : false, department: "National Highway Traffic Safety Administration"},
{ enabled : false, department: "National Historical Publications and Records Commission"},
{ enabled : false, department: "National Indian Gaming Commission"},
{ enabled : false, department: "National Institute for Literacy"},
{ enabled : false, department: "National Institute of Corrections"},
{ enabled : false, department: "National Institute of Food and Agriculture"},
{ enabled : false, department: "National Institute of Justice"},
{ enabled : false, department: "National Institute of Standards and Technology"},
{ enabled : false, department: "National Institutes of Health"},
{ enabled : false, department: "National Intelligence, Office of the National Director"},
{ enabled : false, department: "National Labor Relations Board"},
{ enabled : false, department: "National Library of Medicine"},
{ enabled : false, department: "National Mediation Board"},
{ enabled : false, department: "National Nanotechnology Coordination Office"},
{ enabled : false, department: "National Nuclear Security Administration"},
{ enabled : false, department: "National Oceanic and Atmospheric Administration"},
{ enabled : false, department: "National Park Service"},
{ enabled : false, department: "National Partnership for Reinventing Government"},
{ enabled : false, department: "National Prison Rape Elimination Commission"},
{ enabled : false, department: "National Railroad Passenger Corporation"},
{ enabled : false, department: "National Science Foundation"},
{ enabled : false, department: "National Security Agency/Central Security Service"},
{ enabled : false, department: "National Security Council"},
{ enabled : false, department: "National Shipping Authority"},
{ enabled : false, department: "National Skill Standards Board"},
{ enabled : false, department: "National Technical Information Service"},
{ enabled : false, department: "National Telecommunications and Information Administration"},
{ enabled : false, department: "National Transportation Safety Board"},
{ enabled : false, department: "National Women's Business Council"},
{ enabled : false, department: "Natural Resources Conservation Service"},
{ enabled : false, department: "Natural Resources Revenue Office"},
{ enabled : false, department: "Navajo and Hopi Indian Relocation Office"},
{ enabled : false, department: "Navy Department"},
{ enabled : false, department: "Neighborhood Reinvestment Corporation"},
{ enabled : false, department: "Northeast Dairy Compact Commission"},
{ enabled : false, department: "Northeast Interstate Low-Level Radioactive Waste Commission"},
{ enabled : false, department: "Nuclear Energy Office"},
{ enabled : false, department: "Nuclear Regulatory Commission"},
{ enabled : false, department: "Nuclear Waste Technical Review Board"},
{ enabled : false, department: "Occupational Safety and Health Administration"},
{ enabled : false, department: "Occupational Safety and Health Review Commission"},
{ enabled : false, department: "Ocean Energy Management Bureau"},
{ enabled : false, department: "Ocean Energy Management, Regulation, and Enforcement Bureau"},
{ enabled : false, department: "Ocean Policy Commission"},
{ enabled : false, department: "Office of Government Information Services"},
{ enabled : false, department: "Office of Motor Carrier Safety"},
{ enabled : false, department: "Office of National Drug Control Policy"},
{ enabled : false, department: "Office of Policy Development"},
{ enabled : false, department: "Office of the Chief Financial Officer, Agriculture Department"},
{ enabled : false, department: "Oklahoma City National Memorial Trust"},
{ enabled : false, department: "Operations Office"},
{ enabled : false, department: "Ounce of Prevention Council"},
{ enabled : false, department: "Overseas Private Investment Corporation"},
{ enabled : false, department: "Pacific Northwest Electric Power and Conservation Planning Council"},
{ enabled : false, department: "Panama Canal Commission"},
{ enabled : false, department: "Parole Commission"},
{ enabled : false, department: "Patent and Trademark Office"},
{ enabled : false, department: "Peace Corps"},
{ enabled : false, department: "Pension and Welfare Benefits Administration"},
{ enabled : false, department: "Pension Benefit Guaranty Corporation"},
{ enabled : false, department: "Personnel Management Office"},
{ enabled : false, department: "Physician Payment Review Commission"},
{ enabled : false, department: "Pipeline and Hazardous Materials Safety Administration"},
{ enabled : false, department: "Postal Rate Commission"},
{ enabled : false, department: "Postal Regulatory Commission"},
{ enabled : false, department: "Postal Service"},
{ enabled : false, department: "President's Council on Integrity and Efficiency"},
{ enabled : false, department: "President's Council on Sustainable Development"},
{ enabled : false, department: "President's Critical Infrastructure Protection Board"},
{ enabled : false, department: "President's Economic Policy Advisory Board"},
{ enabled : false, department: "Presidential Advisory Committee on Gulf War Veterans' Illnesses"},
{ enabled : false, department: "Presidential Commission on Assignment of Women in the Armed Forces"},
{ enabled : false, department: "Presidential Documents"},
{ enabled : false, department: "Presidio Trust"},
{ enabled : false, department: "Prisons Bureau"},
{ enabled : false, department: "Privacy and Civil Liberties Oversight Board"},
{ enabled : false, department: "Procurement and Property Management, Office of"},
{ enabled : false, department: "Program Support Center"},
{ enabled : false, department: "Prospective Payment Assessment Commission"},
{ enabled : false, department: "Public Debt Bureau"},
{ enabled : false, department: "Public Health Service"},
{ enabled : false, department: "Railroad Retirement Board"},
{ enabled : false, department: "Reagan-Udall Foundation for the Food and Drug Administration"},
{ enabled : false, department: "Reclamation Bureau"},
{ enabled : false, department: "Recovery Accountability and Transparency Board"},
{ enabled : false, department: "Refugee Resettlement Office"},
{ enabled : false, department: "Regulatory Information Service Center"},
{ enabled : false, department: "Research and Innovative Technology Administration"},
{ enabled : false, department: "Research and Special Programs Administration"},
{ enabled : false, department: "Resolution Trust Corporation"},
{ enabled : false, department: "Risk Management Agency"},
{ enabled : false, department: "Rural Business-Cooperative Service"},
{ enabled : false, department: "Rural Housing and Community Development Service"},
{ enabled : false, department: "Rural Housing Service"},
{ enabled : false, department: "Rural Telephone Bank"},
{ enabled : false, department: "Rural Utilities Service"},
{ enabled : false, department: "Safety and Environmental Enforcement Bureau"},
{ enabled : false, department: "Saint Lawrence Seaway Development Corporation"},
{ enabled : false, department: "Science and Technology Policy Office"},
{ enabled : false, department: "Secret Service"},
{ enabled : false, department: "Securities and Exchange Commission"},
{ enabled : false, department: "Selective Service System"},
{ enabled : false, department: "Small Business Administration"},
{ enabled : false, department: "Smithsonian Institution"},
{ enabled : false, department: "Social Security Administration"},
{ enabled : false, department: "Southeastern Power Administration"},
{ enabled : false, department: "Southwestern Power Administration"},
{ enabled : false, department: "Special Counsel Office"},
{ enabled : false, department: "Special Inspector General for Afghanistan Reconstruction"},
{ enabled : false, department: "Special Inspector General For Iraq Reconstruction"},
{ enabled : false, department: "Special Trustee for American Indians Office"},
{ enabled : false, department: "State Department"},
{ enabled : false, department: "State Justice Institute"},
{ enabled : false, department: "Substance Abuse and Mental Health Services Administration"},
{ enabled : false, department: "Surface Mining Reclamation and Enforcement Office"},
{ enabled : false, department: "Surface Transportation Board"},
{ enabled : false, department: "Susquehanna River Basin Commission"},
{ enabled : false, department: "Technology Administration"},
{ enabled : false, department: "Tennessee Valley Authority"},
{ enabled : false, department: "The White House Office"},
{ enabled : false, department: "Thrift Depositor Protection Oversight Board"},
{ enabled : false, department: "Thrift Supervision Office"},
{ enabled : false, department: "Trade and Development Agency"},
{ enabled : false, department: "Trade Representative, Office of United States"},
{ enabled : false, department: "Transportation Department"},
{ enabled : false, department: "Transportation Office"},
{ enabled : false, department: "Transportation Security Administration"},
{ enabled : false, department: "Transportation Statistics Bureau"},
{ enabled : false, department: "Travel and Tourism Administration"},
{ enabled : false, department: "Treasury Department"},
{ enabled : false, department: "Twenty-First Century Workforce Commission"},
{ enabled : false, department: "U.S. Citizenship and Immigration Services"},
{ enabled : false, department: "U.S. Codex Office"},
{ enabled : false, department: "U.S. Customs and Border Protection"},
{ enabled : false, department: "U.S. House of Representatives"},
{ enabled : false, department: "U.S. Immigration and Customs Enforcement"},
{ enabled : false, department: "U.S. Trade Deficit Review Commission"},
{ enabled : false, department: "U.S.-China Economic and Security Review Commission"},
{ enabled : false, department: "Uniformed Services University of the Health Sciences"},
{ enabled : false, department: "United States Enrichment Corporation"},
{ enabled : false, department: "United States Information Agency"},
{ enabled : false, department: "United States Institute of Peace"},
{ enabled : false, department: "United States Marshals Service"},
{ enabled : false, department: "United States Mint"},
{ enabled : false, department: "United States Sentencing Commission"},
{ enabled : false, department: "Utah Reclamation Mitigation and Conservation Commission"},
{ enabled : false, department: "Valles Caldera Trust"},
{ enabled : false, department: "Veterans Affairs Department"},
{ enabled : false, department: "Veterans Employment and Training Service"},
{ enabled : false, department: "Victims of Crime Office"},
{ enabled : false, department: "Wage and Hour Division"},
{ enabled : false, department: "Western Area Power Administration"},
{ enabled : false, department: "Women's Business Enterprise Interagency Committee"},
{ enabled : false, department: "Women's Progress Commemoration Commission"},
{ enabled : false, department: "Workers Compensation Programs Office"}]

export default allDepartments;