const allDepartments = [{ value: "Administration Office, Executive Office of the President", label: "Administration Office, Executive Office of the President"},
{ value: "Administrative Conference of the United States", label: "Administrative Conference of the United States"},
{ value: "Administrative Office of United States Courts", label: "Administrative Office of United States Courts"},
{ value: "Advisory Council on Historic Preservation", label: "Advisory Council on Historic Preservation"},
{ value: "Advocacy and Outreach Office", label: "Advocacy and Outreach Office"},
{ value: "African Development Foundation", label: "African Development Foundation"},
{ value: "Agency for Healthcare Research and Quality", label: "Agency for Healthcare Research and Quality"},
{ value: "Agency for International Development", label: "Agency for International Development"},
{ value: "Agency for Toxic Substances and Disease Registry", label: "Agency for Toxic Substances and Disease Registry"},
{ value: "Aging Administration", label: "Aging Administration"},
{ value: "Agricultural Marketing Service", label: "Agricultural Marketing Service"},
{ value: "Agricultural Research Service", label: "Agricultural Research Service"},
{ value: "Agriculture Department", label: "Agriculture Department"},
{ value: "Air Force Department", label: "Air Force Department"},
{ value: "Air Quality National Commission", label: "Air Quality National Commission"},
{ value: "Air Transportation Stabilization Board", label: "Air Transportation Stabilization Board"},
{ value: "Alaska Power Administration", label: "Alaska Power Administration"},
{ value: "Alcohol and Tobacco Tax and Trade Bureau", label: "Alcohol and Tobacco Tax and Trade Bureau"},
{ value: "Alcohol, Tobacco, Firearms, and Explosives Bureau", label: "Alcohol, Tobacco, Firearms, and Explosives Bureau"},
{ value: "American Battle Monuments Commission", label: "American Battle Monuments Commission"},
{ value: "Amtrak Reform Council", label: "Amtrak Reform Council"},
{ value: "Animal and Plant Health Inspection Service", label: "Animal and Plant Health Inspection Service"},
{ value: "Antitrust Division", label: "Antitrust Division"},
{ value: "Antitrust Modernization Commission", label: "Antitrust Modernization Commission"},
{ value: "Appalachian Regional Commission", label: "Appalachian Regional Commission"},
{ value: "Appalachian States Low-Level Radioactive Waste Commission", label: "Appalachian States Low-Level Radioactive Waste Commission"},
{ value: "Architect of the Capitol", label: "Architect of the Capitol"},
{ value: "Architectural and Transportation Barriers Compliance Board", label: "Architectural and Transportation Barriers Compliance Board"},
{ value: "Arctic Research Commission", label: "Arctic Research Commission"},
{ value: "Armed Forces Retirement Home", label: "Armed Forces Retirement Home"},
{ value: "Arms Control and Disarmament Agency", label: "Arms Control and Disarmament Agency"},
{ value: "Army Department", label: "Army Department"},
{ value: "Assassination Records Review Board", label: "Assassination Records Review Board"},
{ value: "Barry M. Goldwater Scholarship and Excellence in Education Foundation", label: "Barry M. Goldwater Scholarship and Excellence in Education Foundation"},
{ value: "Benefits Review Board", label: "Benefits Review Board"},
{ value: "Bipartisan Commission on Entitlement and Tax Reform", label: "Bipartisan Commission on Entitlement and Tax Reform"},
{ value: "Board of Directors of the Hope for Homeowners Program", label: "Board of Directors of the Hope for Homeowners Program"},
{ value: "Bonneville Power Administration", label: "Bonneville Power Administration"},
{ value: "Broadcasting Board of Governors", label: "Broadcasting Board of Governors"},
{ value: "Bureau of the Fiscal Service", label: "Bureau of the Fiscal Service"},
{ value: "Census Bureau", label: "Census Bureau"},
{ value: "Census Monitoring Board", label: "Census Monitoring Board"},
{ value: "Centers for Disease Control and Prevention", label: "Centers for Disease Control and Prevention"},
{ value: "Centers for Medicare & Medicaid Services", label: "Centers for Medicare & Medicaid Services"},
{ value: "Central Intelligence Agency", label: "Central Intelligence Agency"},
{ value: "Chemical Safety and Hazard Investigation Board", label: "Chemical Safety and Hazard Investigation Board"},
{ value: "Child Support Enforcement Office", label: "Child Support Enforcement Office"},
{ value: "Children and Families Administration", label: "Children and Families Administration"},
{ value: "Christopher Columbus Quincentenary Jubilee Commission", label: "Christopher Columbus Quincentenary Jubilee Commission"},
{ value: "Civil Rights Commission", label: "Civil Rights Commission"},
{ value: "Coast Guard", label: "Coast Guard"},
{ value: "Commerce Department", label: "Commerce Department"},
{ value: "Commercial Space Transportation Office", label: "Commercial Space Transportation Office"},
{ value: "Commission of Fine Arts", label: "Commission of Fine Arts"},
{ value: "Commission on Immigration Reform", label: "Commission on Immigration Reform"},
{ value: "Commission on Protecting and Reducing Government Secrecy", label: "Commission on Protecting and Reducing Government Secrecy"},
{ value: "Commission on Review of Overseas Military Facility Structure of the United States", label: "Commission on Review of Overseas Military Facility Structure of the United States"},
{ value: "Commission on Structural Alternatives for the Federal Courts of Appeals", label: "Commission on Structural Alternatives for the Federal Courts of Appeals"},
{ value: "Commission on the Advancement of Federal Law Enforcement", label: "Commission on the Advancement of Federal Law Enforcement"},
{ value: "Commission on the Bicentennial of the United States Constitution", label: "Commission on the Bicentennial of the United States Constitution"},
{ value: "Commission on the Future of the United States Aerospace Industry", label: "Commission on the Future of the United States Aerospace Industry"},
{ value: "Commission on the Social Security Notch Issue", label: "Commission on the Social Security Notch Issue"},
{ value: "Committee for Purchase From People Who Are Blind or Severely Disabled", label: "Committee for Purchase From People Who Are Blind or Severely Disabled"},
{ value: "Committee for the Implementation of Textile Agreements", label: "Committee for the Implementation of Textile Agreements"},
{ value: "Commodity Credit Corporation", label: "Commodity Credit Corporation"},
{ value: "Commodity Futures Trading Commission", label: "Commodity Futures Trading Commission"},
{ value: "Community Development Financial Institutions Fund", label: "Community Development Financial Institutions Fund"},
{ value: "Community Living Administration", label: "Community Living Administration"},
{ value: "Competitiveness Policy Council", label: "Competitiveness Policy Council"},
{ value: "Comptroller of the Currency", label: "Comptroller of the Currency"},
{ value: "Congressional Budget Office", label: "Congressional Budget Office"},
{ value: "Consumer Financial Protection Bureau", label: "Consumer Financial Protection Bureau"},
{ value: "Consumer Product Safety Commission", label: "Consumer Product Safety Commission"},
{ value: "Cooperative State Research, Education, and Extension Service", label: "Cooperative State Research, Education, and Extension Service"},
{ value: "Coordinating Council on Juvenile Justice and Delinquency Prevention", label: "Coordinating Council on Juvenile Justice and Delinquency Prevention"},
{ value: "Copyright Office, Library of Congress", label: "Copyright Office, Library of Congress"},
{ value: "Copyright Royalty Board", label: "Copyright Royalty Board"},
{ value: "Copyright Royalty Judges", label: "Copyright Royalty Judges"},
{ value: "Corporation for National and Community Service", label: "Corporation for National and Community Service"},
{ value: "Council of the Inspectors General on Integrity and Efficiency", label: "Council of the Inspectors General on Integrity and Efficiency"},
{ value: "Council on Environmental Quality", label: "Council on Environmental Quality"},
{ value: "Counsel to the President", label: "Counsel to the President"},
{ value: "Court Services and Offender Supervision Agency for the District of Columbia", label: "Court Services and Offender Supervision Agency for the District of Columbia"},
{ value: "Crime and Security in U.S. Seaports, Interagency Commission", label: "Crime and Security in U.S. Seaports, Interagency Commission"},
{ value: "Customs Service", label: "Customs Service"},
{ value: "Defense Acquisition Regulations System", label: "Defense Acquisition Regulations System"},
{ value: "Defense Base Closure and Realignment Commission", label: "Defense Base Closure and Realignment Commission"},
{ value: "Defense Contract Audit Agency", label: "Defense Contract Audit Agency"},
{ value: "Defense Criminal Investigative Service", label: "Defense Criminal Investigative Service"},
{ value: "Defense Department", label: "Defense Department"},
{ value: "Defense Information Systems Agency", label: "Defense Information Systems Agency"},
{ value: "Defense Intelligence Agency", label: "Defense Intelligence Agency"},
{ value: "Defense Investigative Service", label: "Defense Investigative Service"},
{ value: "Defense Logistics Agency", label: "Defense Logistics Agency"},
{ value: "Defense Mapping Agency", label: "Defense Mapping Agency"},
{ value: "Defense Nuclear Facilities Safety Board", label: "Defense Nuclear Facilities Safety Board"},
{ value: "Defense Special Weapons Agency", label: "Defense Special Weapons Agency"},
{ value: "Delaware River Basin Commission", label: "Delaware River Basin Commission"},
{ value: "Denali Commission", label: "Denali Commission"},
{ value: "Disability Employment Policy Office", label: "Disability Employment Policy Office"},
{ value: "Drug Enforcement Administration", label: "Drug Enforcement Administration"},
{ value: "Economic Analysis Bureau", label: "Economic Analysis Bureau"},
{ value: "Economic Analysis Staff", label: "Economic Analysis Staff"},
{ value: "Economic Development Administration", label: "Economic Development Administration"},
{ value: "Economic Research Service", label: "Economic Research Service"},
{ value: "Economics and Statistics Administration", label: "Economics and Statistics Administration"},
{ value: "Education Department", label: "Education Department"},
{ value: "Election Assistance Commission", label: "Election Assistance Commission"},
{ value: "Electronic Commerce Advisory Commission", label: "Electronic Commerce Advisory Commission"},
{ value: "Emergency Oil and Gas Guaranteed Loan Board", label: "Emergency Oil and Gas Guaranteed Loan Board"},
{ value: "Emergency Steel Guarantee Loan Board", label: "Emergency Steel Guarantee Loan Board"},
{ value: "Employee Benefits Security Administration", label: "Employee Benefits Security Administration"},
{ value: "Employees Compensation Appeals Board", label: "Employees Compensation Appeals Board"},
{ value: "Employment and Training Administration", label: "Employment and Training Administration"},
{ value: "Employment Standards Administration", label: "Employment Standards Administration"},
{ value: "Energy Department", label: "Energy Department"},
{ value: "Energy Efficiency and Renewable Energy Office", label: "Energy Efficiency and Renewable Energy Office"},
{ value: "Energy Information Administration", label: "Energy Information Administration"},
{ value: "Energy Policy and New Uses Office", label: "Energy Policy and New Uses Office"},
{ value: "Energy Research Office", label: "Energy Research Office"},
{ value: "Engineers Corps", label: "Engineers Corps"},
{ value: "Engraving and Printing Bureau", label: "Engraving and Printing Bureau"},
{ value: "Environment Office, Energy Department", label: "Environment Office, Energy Department"},
{ value: "Environmental Protection Agency", label: "Environmental Protection Agency"},
{ value: "Equal Employment Opportunity Commission", label: "Equal Employment Opportunity Commission"},
{ value: "Executive Council on Integrity and Efficiency", label: "Executive Council on Integrity and Efficiency"},
{ value: "Executive Office for Immigration Review", label: "Executive Office for Immigration Review"},
{ value: "Executive Office of the President", label: "Executive Office of the President"},
{ value: "Export Administration Bureau", label: "Export Administration Bureau"},
{ value: "Export-Import Bank", label: "Export-Import Bank"},
{ value: "Family Assistance Office", label: "Family Assistance Office"},
{ value: "Farm Credit Administration", label: "Farm Credit Administration"},
{ value: "Farm Credit System Insurance Corporation", label: "Farm Credit System Insurance Corporation"},
{ value: "Farm Service Agency", label: "Farm Service Agency"},
{ value: "Federal Accounting Standards Advisory Board", label: "Federal Accounting Standards Advisory Board"},
{ value: "Federal Acquisition Regulation System", label: "Federal Acquisition Regulation System"},
{ value: "Federal Aviation Administration", label: "Federal Aviation Administration"},
{ value: "Federal Bureau of Investigation", label: "Federal Bureau of Investigation"},
{ value: "Federal Communications Commission", label: "Federal Communications Commission"},
{ value: "Federal Contract Compliance Programs Office", label: "Federal Contract Compliance Programs Office"},
{ value: "Federal Council on the Arts and the Humanities", label: "Federal Council on the Arts and the Humanities"},
{ value: "Federal Crop Insurance Corporation", label: "Federal Crop Insurance Corporation"},
{ value: "Federal Deposit Insurance Corporation", label: "Federal Deposit Insurance Corporation"},
{ value: "Federal Election Commission", label: "Federal Election Commission"},
{ value: "Federal Emergency Management Agency", label: "Federal Emergency Management Agency"},
{ value: "Federal Energy Regulatory Commission", label: "Federal Energy Regulatory Commission"},
{ value: "Federal Financial Institutions Examination Council", label: "Federal Financial Institutions Examination Council"},
{ value: "Federal Highway Administration", label: "Federal Highway Administration"},
{ value: "Federal Housing Enterprise Oversight Office", label: "Federal Housing Enterprise Oversight Office"},
{ value: "Federal Housing Finance Agency", label: "Federal Housing Finance Agency"},
{ value: "Federal Housing Finance Board", label: "Federal Housing Finance Board"},
{ value: "Federal Labor Relations Authority", label: "Federal Labor Relations Authority"},
{ value: "Federal Law Enforcement Training Center", label: "Federal Law Enforcement Training Center"},
{ value: "Federal Maritime Commission", label: "Federal Maritime Commission"},
{ value: "Federal Mediation and Conciliation Service", label: "Federal Mediation and Conciliation Service"},
{ value: "Federal Mine Safety and Health Review Commission", label: "Federal Mine Safety and Health Review Commission"},
{ value: "Federal Motor Carrier Safety Administration", label: "Federal Motor Carrier Safety Administration"},
{ value: "Federal Pay, Advisory Committee", label: "Federal Pay, Advisory Committee"},
{ value: "Federal Permitting Improvement Steering Council", label: "Federal Permitting Improvement Steering Council"},
{ value: "Federal Prison Industries", label: "Federal Prison Industries"},
{ value: "Federal Procurement Policy Office", label: "Federal Procurement Policy Office"},
{ value: "Federal Railroad Administration", label: "Federal Railroad Administration"},
{ value: "Federal Register Office", label: "Federal Register Office"},
{ value: "Federal Register, Administrative Committee", label: "Federal Register, Administrative Committee"},
{ value: "Federal Reserve System", label: "Federal Reserve System"},
{ value: "Federal Retirement Thrift Investment Board", label: "Federal Retirement Thrift Investment Board"},
{ value: "Federal Service Impasses Panel", label: "Federal Service Impasses Panel"},
{ value: "Federal Trade Commission", label: "Federal Trade Commission"},
{ value: "Federal Transit Administration", label: "Federal Transit Administration"},
{ value: "Financial Crimes Enforcement Network", label: "Financial Crimes Enforcement Network"},
{ value: "Financial Crisis Inquiry Commission", label: "Financial Crisis Inquiry Commission"},
{ value: "Financial Research Office", label: "Financial Research Office"},
{ value: "Financial Stability Oversight Council", label: "Financial Stability Oversight Council"},
{ value: "First Responder Network Authority", label: "First Responder Network Authority"},
{ value: "Fiscal Service", label: "Fiscal Service"},
{ value: "Fish and Wildlife Service", label: "Fish and Wildlife Service"},
{ value: "Food and Consumer Service", label: "Food and Consumer Service"},
{ value: "Food and Drug Administration", label: "Food and Drug Administration"},
{ value: "Food and Nutrition Service", label: "Food and Nutrition Service"},
{ value: "Food Safety and Inspection Service", label: "Food Safety and Inspection Service"},
{ value: "Foreign Agricultural Service", label: "Foreign Agricultural Service"},
{ value: "Foreign Assets Control Office", label: "Foreign Assets Control Office"},
{ value: "Foreign Claims Settlement Commission", label: "Foreign Claims Settlement Commission"},
{ value: "Foreign Service Grievance Board", label: "Foreign Service Grievance Board"},
{ value: "Foreign Service Impasse Disputes Panel", label: "Foreign Service Impasse Disputes Panel"},
{ value: "Foreign Service Labor Relations Board", label: "Foreign Service Labor Relations Board"},
{ value: "Foreign-Trade Zones Board", label: "Foreign-Trade Zones Board"},
{ value: "Forest Service", label: "Forest Service"},
{ value: "General Services Administration", label: "General Services Administration"},
{ value: "Geographic Names Board", label: "Geographic Names Board"},
{ value: "Geological Survey", label: "Geological Survey"},
{ value: "Government Accountability Office", label: "Government Accountability Office"},
{ value: "Government Ethics Office", label: "Government Ethics Office"},
{ value: "Government National Mortgage Association", label: "Government National Mortgage Association"},
{ value: "Government Publishing Office", label: "Government Publishing Office"},
{ value: "Grain Inspection, Packers and Stockyards Administration", label: "Grain Inspection, Packers and Stockyards Administration"},
{ value: "Gulf Coast Ecosystem Restoration Council", label: "Gulf Coast Ecosystem Restoration Council"},
{ value: "Harry S. Truman Scholarship Foundation", label: "Harry S. Truman Scholarship Foundation"},
{ value: "Health and Human Services Department", label: "Health and Human Services Department"},
{ value: "Health Care Finance Administration", label: "Health Care Finance Administration"},
{ value: "Health Resources and Services Administration", label: "Health Resources and Services Administration"},
{ value: "Hearings and Appeals Office, Energy Department", label: "Hearings and Appeals Office, Energy Department"},
{ value: "Hearings and Appeals Office, Interior Department", label: "Hearings and Appeals Office, Interior Department"},
{ value: "Homeland Security Department", label: "Homeland Security Department"},
{ value: "Housing and Urban Development Department", label: "Housing and Urban Development Department"},
{ value: "Immigration and Naturalization Service", label: "Immigration and Naturalization Service"},
{ value: "Indian Affairs Bureau", label: "Indian Affairs Bureau"},
{ value: "Indian Arts and Crafts Board", label: "Indian Arts and Crafts Board"},
{ value: "Indian Health Service", label: "Indian Health Service"},
{ value: "Indian Trust Transition Office", label: "Indian Trust Transition Office"},
{ value: "Industry and Security Bureau", label: "Industry and Security Bureau"},
{ value: "Information Security Oversight Office", label: "Information Security Oversight Office"},
{ value: "Inspector General Office, Agriculture Department", label: "Inspector General Office, Agriculture Department"},
{ value: "Inspector General Office, Health and Human Services Department", label: "Inspector General Office, Health and Human Services Department"},
{ value: "Institute of American Indian and Alaska Native Culture and Arts Development", label: "Institute of American Indian and Alaska Native Culture and Arts Development"},
{ value: "Institute of Museum and Library Services", label: "Institute of Museum and Library Services"},
{ value: "Inter-American Foundation", label: "Inter-American Foundation"},
{ value: "Interagency Floodplain Management Review Committee", label: "Interagency Floodplain Management Review Committee"},
{ value: "Intergovernmental Relations Advisory Commission", label: "Intergovernmental Relations Advisory Commission"},
{ value: "Interior Department", label: "Interior Department"},
{ value: "Internal Revenue Service", label: "Internal Revenue Service"},
{ value: "International Boundary and Water Commission, United States and Mexico", label: "International Boundary and Water Commission, United States and Mexico"},
{ value: "International Broadcasting Board", label: "International Broadcasting Board"},
{ value: "International Development Cooperation Agency", label: "International Development Cooperation Agency"},
{ value: "International Investment Office", label: "International Investment Office"},
{ value: "International Joint Commission-United States and Canada", label: "International Joint Commission-United States and Canada"},
{ value: "International Organizations Employees Loyalty Board", label: "International Organizations Employees Loyalty Board"},
{ value: "International Trade Administration", label: "International Trade Administration"},
{ value: "International Trade Commission", label: "International Trade Commission"},
{ value: "Interstate Commerce Commission", label: "Interstate Commerce Commission"},
{ value: "James Madison Memorial Fellowship Foundation", label: "James Madison Memorial Fellowship Foundation"},
{ value: "Japan-United States Friendship Commission", label: "Japan-United States Friendship Commission"},
{ value: "Joint Board for Enrollment of Actuaries", label: "Joint Board for Enrollment of Actuaries"},
{ value: "Judicial Conference of the United States", label: "Judicial Conference of the United States"},
{ value: "Judicial Review Commission on Foreign Asset Control", label: "Judicial Review Commission on Foreign Asset Control"},
{ value: "Justice Department", label: "Justice Department"},
{ value: "Justice Programs Office", label: "Justice Programs Office"},
{ value: "Juvenile Justice and Delinquency Prevention Office", label: "Juvenile Justice and Delinquency Prevention Office"},
{ value: "Labor Department", label: "Labor Department"},
{ value: "Labor Statistics Bureau", label: "Labor Statistics Bureau"},
{ value: "Labor-Management Standards Office", label: "Labor-Management Standards Office"},
{ value: "Land Management Bureau", label: "Land Management Bureau"},
{ value: "Legal Services Corporation", label: "Legal Services Corporation"},
{ value: "Library of Congress", label: "Library of Congress"},
{ value: "Local Television Loan Guarantee Board", label: "Local Television Loan Guarantee Board"},
{ value: "Management and Budget Office", label: "Management and Budget Office"},
{ value: "Marine Mammal Commission", label: "Marine Mammal Commission"},
{ value: "Maritime Administration", label: "Maritime Administration"},
{ value: "Medicare Payment Advisory Commission", label: "Medicare Payment Advisory Commission"},
{ value: "Merit Systems Protection Board", label: "Merit Systems Protection Board"},
{ value: "Military Compensation and Retirement Modernization Commission", label: "Military Compensation and Retirement Modernization Commission"},
{ value: "Millennium Challenge Corporation", label: "Millennium Challenge Corporation"},
{ value: "Mine Safety and Health Administration", label: "Mine Safety and Health Administration"},
{ value: "Minerals Management Service", label: "Minerals Management Service"},
{ value: "Mines Bureau", label: "Mines Bureau"},
{ value: "Minority Business Development Agency", label: "Minority Business Development Agency"},
{ value: "Minority Economic Impact Office", label: "Minority Economic Impact Office"},
{ value: "Mississippi River Commission", label: "Mississippi River Commission"},
{ value: "Monetary Offices", label: "Monetary Offices"},
{ value: "Morris K. Udall and Stewart L. Udall Foundation", label: "Morris K. Udall and Stewart L. Udall Foundation"},
{ value: "National Aeronautics and Space Administration", label: "National Aeronautics and Space Administration"},
{ value: "National Agricultural Library", label: "National Agricultural Library"},
{ value: "National Agricultural Statistics Service", label: "National Agricultural Statistics Service"},
{ value: "National Archives and Records Administration", label: "National Archives and Records Administration"},
{ value: "National Bankruptcy Review Commission", label: "National Bankruptcy Review Commission"},
{ value: "National Biological Service", label: "National Biological Service"},
{ value: "National Bipartisan Commission on Future of Medicare", label: "National Bipartisan Commission on Future of Medicare"},
{ value: "National Capital Planning Commission", label: "National Capital Planning Commission"},
{ value: "National Civilian Community Corps", label: "National Civilian Community Corps"},
{ value: "National Commission on Fiscal Responsibility and Reform", label: "National Commission on Fiscal Responsibility and Reform"},
{ value: "National Commission on Intermodal Transportation", label: "National Commission on Intermodal Transportation"},
{ value: "National Commission on Libraries and Information Science", label: "National Commission on Libraries and Information Science"},
{ value: "National Commission on Manufactured Housing", label: "National Commission on Manufactured Housing"},
{ value: "National Commission on Military, National, and Public Service", label: "National Commission on Military, National, and Public Service"},
{ value: "National Commission on Terrorist Attacks Upon the United States", label: "National Commission on Terrorist Attacks Upon the United States"},
{ value: "National Commission on the Cost of Higher Education", label: "National Commission on the Cost of Higher Education"},
{ value: "National Communications System", label: "National Communications System"},
{ value: "National Consumer Cooperative Bank", label: "National Consumer Cooperative Bank"},
{ value: "National Council on Disability", label: "National Council on Disability"},
{ value: "National Counterintelligence Center", label: "National Counterintelligence Center"},
{ value: "National Credit Union Administration", label: "National Credit Union Administration"},
{ value: "National Crime Prevention and Privacy Compact Council", label: "National Crime Prevention and Privacy Compact Council"},
{ value: "National Economic Council", label: "National Economic Council"},
{ value: "National Education Goals Panel", label: "National Education Goals Panel"},
{ value: "National Endowment for the Arts", label: "National Endowment for the Arts"},
{ value: "National Endowment for the Humanities", label: "National Endowment for the Humanities"},
{ value: "National Foundation on the Arts and the Humanities", label: "National Foundation on the Arts and the Humanities"},
{ value: "National Gambling Impact Study Commission", label: "National Gambling Impact Study Commission"},
{ value: "National Geospatial-Intelligence Agency", label: "National Geospatial-Intelligence Agency"},
{ value: "National Highway Traffic Safety Administration", label: "National Highway Traffic Safety Administration"},
{ value: "National Historical Publications and Records Commission", label: "National Historical Publications and Records Commission"},
{ value: "National Indian Gaming Commission", label: "National Indian Gaming Commission"},
{ value: "National Institute for Literacy", label: "National Institute for Literacy"},
{ value: "National Institute of Corrections", label: "National Institute of Corrections"},
{ value: "National Institute of Food and Agriculture", label: "National Institute of Food and Agriculture"},
{ value: "National Institute of Justice", label: "National Institute of Justice"},
{ value: "National Institute of Standards and Technology", label: "National Institute of Standards and Technology"},
{ value: "National Institutes of Health", label: "National Institutes of Health"},
{ value: "National Intelligence, Office of the National Director", label: "National Intelligence, Office of the National Director"},
{ value: "National Labor Relations Board", label: "National Labor Relations Board"},
{ value: "National Library of Medicine", label: "National Library of Medicine"},
{ value: "National Mediation Board", label: "National Mediation Board"},
{ value: "National Nanotechnology Coordination Office", label: "National Nanotechnology Coordination Office"},
{ value: "National Nuclear Security Administration", label: "National Nuclear Security Administration"},
{ value: "National Oceanic and Atmospheric Administration", label: "National Oceanic and Atmospheric Administration"},
{ value: "National Park Service", label: "National Park Service"},
{ value: "National Partnership for Reinventing Government", label: "National Partnership for Reinventing Government"},
{ value: "National Prison Rape Elimination Commission", label: "National Prison Rape Elimination Commission"},
{ value: "National Railroad Passenger Corporation", label: "National Railroad Passenger Corporation"},
{ value: "National Science Foundation", label: "National Science Foundation"},
{ value: "National Security Agency/Central Security Service", label: "National Security Agency/Central Security Service"},
{ value: "National Security Council", label: "National Security Council"},
{ value: "National Shipping Authority", label: "National Shipping Authority"},
{ value: "National Skill Standards Board", label: "National Skill Standards Board"},
{ value: "National Technical Information Service", label: "National Technical Information Service"},
{ value: "National Telecommunications and Information Administration", label: "National Telecommunications and Information Administration"},
{ value: "National Transportation Safety Board", label: "National Transportation Safety Board"},
{ value: "National Women's Business Council", label: "National Women's Business Council"},
{ value: "Natural Resources Conservation Service", label: "Natural Resources Conservation Service"},
{ value: "Natural Resources Revenue Office", label: "Natural Resources Revenue Office"},
{ value: "Navajo and Hopi Indian Relocation Office", label: "Navajo and Hopi Indian Relocation Office"},
{ value: "Navy Department", label: "Navy Department"},
{ value: "Neighborhood Reinvestment Corporation", label: "Neighborhood Reinvestment Corporation"},
{ value: "Northeast Dairy Compact Commission", label: "Northeast Dairy Compact Commission"},
{ value: "Northeast Interstate Low-Level Radioactive Waste Commission", label: "Northeast Interstate Low-Level Radioactive Waste Commission"},
{ value: "Nuclear Energy Office", label: "Nuclear Energy Office"},
{ value: "Nuclear Regulatory Commission", label: "Nuclear Regulatory Commission"},
{ value: "Nuclear Waste Technical Review Board", label: "Nuclear Waste Technical Review Board"},
{ value: "Occupational Safety and Health Administration", label: "Occupational Safety and Health Administration"},
{ value: "Occupational Safety and Health Review Commission", label: "Occupational Safety and Health Review Commission"},
{ value: "Ocean Energy Management Bureau", label: "Ocean Energy Management Bureau"},
{ value: "Ocean Energy Management, Regulation, and Enforcement Bureau", label: "Ocean Energy Management, Regulation, and Enforcement Bureau"},
{ value: "Ocean Policy Commission", label: "Ocean Policy Commission"},
{ value: "Office of Government Information Services", label: "Office of Government Information Services"},
{ value: "Office of Motor Carrier Safety", label: "Office of Motor Carrier Safety"},
{ value: "Office of National Drug Control Policy", label: "Office of National Drug Control Policy"},
{ value: "Office of Policy Development", label: "Office of Policy Development"},
{ value: "Office of the Chief Financial Officer, Agriculture Department", label: "Office of the Chief Financial Officer, Agriculture Department"},
{ value: "Oklahoma City National Memorial Trust", label: "Oklahoma City National Memorial Trust"},
{ value: "Operations Office", label: "Operations Office"},
{ value: "Ounce of Prevention Council", label: "Ounce of Prevention Council"},
{ value: "Overseas Private Investment Corporation", label: "Overseas Private Investment Corporation"},
{ value: "Pacific Northwest Electric Power and Conservation Planning Council", label: "Pacific Northwest Electric Power and Conservation Planning Council"},
{ value: "Panama Canal Commission", label: "Panama Canal Commission"},
{ value: "Parole Commission", label: "Parole Commission"},
{ value: "Patent and Trademark Office", label: "Patent and Trademark Office"},
{ value: "Peace Corps", label: "Peace Corps"},
{ value: "Pension and Welfare Benefits Administration", label: "Pension and Welfare Benefits Administration"},
{ value: "Pension Benefit Guaranty Corporation", label: "Pension Benefit Guaranty Corporation"},
{ value: "Personnel Management Office", label: "Personnel Management Office"},
{ value: "Physician Payment Review Commission", label: "Physician Payment Review Commission"},
{ value: "Pipeline and Hazardous Materials Safety Administration", label: "Pipeline and Hazardous Materials Safety Administration"},
{ value: "Postal Rate Commission", label: "Postal Rate Commission"},
{ value: "Postal Regulatory Commission", label: "Postal Regulatory Commission"},
{ value: "Postal Service", label: "Postal Service"},
{ value: "President's Council on Integrity and Efficiency", label: "President's Council on Integrity and Efficiency"},
{ value: "President's Council on Sustainable Development", label: "President's Council on Sustainable Development"},
{ value: "President's Critical Infrastructure Protection Board", label: "President's Critical Infrastructure Protection Board"},
{ value: "President's Economic Policy Advisory Board", label: "President's Economic Policy Advisory Board"},
{ value: "Presidential Advisory Committee on Gulf War Veterans' Illnesses", label: "Presidential Advisory Committee on Gulf War Veterans' Illnesses"},
{ value: "Presidential Commission on Assignment of Women in the Armed Forces", label: "Presidential Commission on Assignment of Women in the Armed Forces"},
{ value: "Presidential Documents", label: "Presidential Documents"},
{ value: "Presidio Trust", label: "Presidio Trust"},
{ value: "Prisons Bureau", label: "Prisons Bureau"},
{ value: "Privacy and Civil Liberties Oversight Board", label: "Privacy and Civil Liberties Oversight Board"},
{ value: "Procurement and Property Management, Office of", label: "Procurement and Property Management, Office of"},
{ value: "Program Support Center", label: "Program Support Center"},
{ value: "Prospective Payment Assessment Commission", label: "Prospective Payment Assessment Commission"},
{ value: "Public Debt Bureau", label: "Public Debt Bureau"},
{ value: "Public Health Service", label: "Public Health Service"},
{ value: "Railroad Retirement Board", label: "Railroad Retirement Board"},
{ value: "Reagan-Udall Foundation for the Food and Drug Administration", label: "Reagan-Udall Foundation for the Food and Drug Administration"},
{ value: "Reclamation Bureau", label: "Reclamation Bureau"},
{ value: "Recovery Accountability and Transparency Board", label: "Recovery Accountability and Transparency Board"},
{ value: "Refugee Resettlement Office", label: "Refugee Resettlement Office"},
{ value: "Regulatory Information Service Center", label: "Regulatory Information Service Center"},
{ value: "Research and Innovative Technology Administration", label: "Research and Innovative Technology Administration"},
{ value: "Research and Special Programs Administration", label: "Research and Special Programs Administration"},
{ value: "Resolution Trust Corporation", label: "Resolution Trust Corporation"},
{ value: "Risk Management Agency", label: "Risk Management Agency"},
{ value: "Rural Business-Cooperative Service", label: "Rural Business-Cooperative Service"},
{ value: "Rural Housing and Community Development Service", label: "Rural Housing and Community Development Service"},
{ value: "Rural Housing Service", label: "Rural Housing Service"},
{ value: "Rural Telephone Bank", label: "Rural Telephone Bank"},
{ value: "Rural Utilities Service", label: "Rural Utilities Service"},
{ value: "Safety and Environmental Enforcement Bureau", label: "Safety and Environmental Enforcement Bureau"},
{ value: "Saint Lawrence Seaway Development Corporation", label: "Saint Lawrence Seaway Development Corporation"},
{ value: "Science and Technology Policy Office", label: "Science and Technology Policy Office"},
{ value: "Secret Service", label: "Secret Service"},
{ value: "Securities and Exchange Commission", label: "Securities and Exchange Commission"},
{ value: "Selective Service System", label: "Selective Service System"},
{ value: "Small Business Administration", label: "Small Business Administration"},
{ value: "Smithsonian Institution", label: "Smithsonian Institution"},
{ value: "Social Security Administration", label: "Social Security Administration"},
{ value: "Southeastern Power Administration", label: "Southeastern Power Administration"},
{ value: "Southwestern Power Administration", label: "Southwestern Power Administration"},
{ value: "Special Counsel Office", label: "Special Counsel Office"},
{ value: "Special Inspector General for Afghanistan Reconstruction", label: "Special Inspector General for Afghanistan Reconstruction"},
{ value: "Special Inspector General For Iraq Reconstruction", label: "Special Inspector General For Iraq Reconstruction"},
{ value: "Special Trustee for American Indians Office", label: "Special Trustee for American Indians Office"},
{ value: "State Department", label: "State Department"},
{ value: "State Justice Institute", label: "State Justice Institute"},
{ value: "Substance Abuse and Mental Health Services Administration", label: "Substance Abuse and Mental Health Services Administration"},
{ value: "Surface Mining Reclamation and Enforcement Office", label: "Surface Mining Reclamation and Enforcement Office"},
{ value: "Surface Transportation Board", label: "Surface Transportation Board"},
{ value: "Susquehanna River Basin Commission", label: "Susquehanna River Basin Commission"},
{ value: "Technology Administration", label: "Technology Administration"},
{ value: "Tennessee Valley Authority", label: "Tennessee Valley Authority"},
{ value: "The White House Office", label: "The White House Office"},
{ value: "Thrift Depositor Protection Oversight Board", label: "Thrift Depositor Protection Oversight Board"},
{ value: "Thrift Supervision Office", label: "Thrift Supervision Office"},
{ value: "Trade and Development Agency", label: "Trade and Development Agency"},
{ value: "Trade Representative, Office of United States", label: "Trade Representative, Office of United States"},
{ value: "Transportation Department", label: "Transportation Department"},
{ value: "Transportation Office", label: "Transportation Office"},
{ value: "Transportation Security Administration", label: "Transportation Security Administration"},
{ value: "Transportation Statistics Bureau", label: "Transportation Statistics Bureau"},
{ value: "Travel and Tourism Administration", label: "Travel and Tourism Administration"},
{ value: "Treasury Department", label: "Treasury Department"},
{ value: "Twenty-First Century Workforce Commission", label: "Twenty-First Century Workforce Commission"},
{ value: "U.S. Citizenship and Immigration Services", label: "U.S. Citizenship and Immigration Services"},
{ value: "U.S. Codex Office", label: "U.S. Codex Office"},
{ value: "U.S. Customs and Border Protection", label: "U.S. Customs and Border Protection"},
{ value: "U.S. House of Representatives", label: "U.S. House of Representatives"},
{ value: "U.S. Immigration and Customs Enforcement", label: "U.S. Immigration and Customs Enforcement"},
{ value: "U.S. Trade Deficit Review Commission", label: "U.S. Trade Deficit Review Commission"},
{ value: "U.S.-China Economic and Security Review Commission", label: "U.S.-China Economic and Security Review Commission"},
{ value: "Uniformed Services University of the Health Sciences", label: "Uniformed Services University of the Health Sciences"},
{ value: "United States Enrichment Corporation", label: "United States Enrichment Corporation"},
{ value: "United States Information Agency", label: "United States Information Agency"},
{ value: "United States Institute of Peace", label: "United States Institute of Peace"},
{ value: "United States Marshals Service", label: "United States Marshals Service"},
{ value: "United States Mint", label: "United States Mint"},
{ value: "United States Sentencing Commission", label: "United States Sentencing Commission"},
{ value: "Utah Reclamation Mitigation and Conservation Commission", label: "Utah Reclamation Mitigation and Conservation Commission"},
{ value: "Valles Caldera Trust", label: "Valles Caldera Trust"},
{ value: "Veterans Affairs Department", label: "Veterans Affairs Department"},
{ value: "Veterans Employment and Training Service", label: "Veterans Employment and Training Service"},
{ value: "Victims of Crime Office", label: "Victims of Crime Office"},
{ value: "Wage and Hour Division", label: "Wage and Hour Division"},
{ value: "Western Area Power Administration", label: "Western Area Power Administration"},
{ value: "Women's Business Enterprise Interagency Committee", label: "Women's Business Enterprise Interagency Committee"},
{ value: "Women's Progress Commemoration Commission", label: "Women's Progress Commemoration Commission"},
{ value: "Workers Compensation Programs Office", label: "Workers Compensation Programs Office"}]

export default allDepartments;